### ISSUE TITLE
Error reported (Cannot locate Apex Type) when using Time Warp on Cases

### ISSUE THREAD

**Issue by sriramdadra** [deejay-hub/timeline-lwc#100]
The component is throwing an error under Cases. Note: Cases are associated to Person Accounts

![Timeline Component Error in Cases](https://user-images.githubusercontent.com/47834822/100808264-aba3cc80-33e8-11eb-9252-1a021fc4366b.PNG)

**"Cannot locate Apex Type for ID: 00a2R00000daJfsQAE : Class.bmpyrckt.TimelineService.getFieldValues: line 428, column 1 Class.bmpyrckt.TimelineService.getTimelineRecords: line 269, column 1"**

**Comment by deejay-hub** [comment]
Oh that's no good @sriramdadra. Looks like the issue is with trying to plot CaseComments. Can you locate the metadata for CaseComments and inactivate it to see if it resolves the error. Navigate to Setup->Custom Metadata Types the locate the Case_CaseComment record and edit it. Then set the active flag to false and save the record. Then refresh the browser. If you could confirm this removes the error we can work on a fix. Thanks in advance.

![image](https://user-images.githubusercontent.com/7021883/100809816-2291a180-348b-11eb-9c4e-63753b0df562.png)

**Comment by deejay-hub** [comment]
When you call the getSObjectType() Apex method to an Id object to get an sObjectType from the Id, we internally call the method and try to get a Type from an entity info returned from it. And in this method call, an entity info is retrieved from a key prefix of the specified Id. However, if the key prefix points to a template entity, the method call returns null since template entities cannot reveal their entity infos. In case of **CaseComment**, it shares its key prefix with **CaseObjectComment**. So, when we try to obtain the entity info using an Id of a CaseComment, we do that through CaseObjectComment. But, since CaseObjectComment is a template entity, we cannot get its entity info. It causes the issue.

We need to somehow verify that only CaseComment is impacted and perhaps use getSObjectType() instead for these edge cases.

**Comment by sriramdadra** [comment]
Hi, I inactivated the 'Case_CaseComments' metadata and the timeline component showed up without any issues.

**Comment by deejay-hub** [comment]
Thanks @sriramdadra. This will have to be a known issue for now. I'll modify the title and include a proper fix in the next release. For now it won't be possible to plot Case Comments. Thanks for your prompt help and time in logging the issue.
