### ISSUE TITLE
Timeline does not seem to show children records of a same Object

### ISSUE THREAD

**Issue by marcbourlon** [deejay-hub/timeline-lwc#133]
**Describe the bug**
Does not display children of the same object type.

**To reproduce**
Steps to reproduce the behaviour:

1. Create a custom object, with a lookup to itself, and one date field
2. Create one record of this object, then few children of the same object
3. Create a new Timeline configuration
4. Set the configuration with the **Parent Object** and the **Object Name** fields to your custom object name
5. Set all the other fields as needed
6. Add the component to the custom object page
7. The page says: No data to display

**Expected behaviour**
The children are shown on the timeline

**Desktop (please complete the following information):**

-   OS: Mac OS
-   Browser: Chrome (it's not a browser issue anyway)
-   Version: Version 91.0.4472.106 (Official Build) (arm64)

**Comment by deejay-hub** [comment]
Thanks for raising the issue. Here are the steps we have tried to replicate the issue.
1. Create a custom object, with a lookup to itself and one date field
We create Memo__c with Start_Date__c and Parent_Memo__c as the lookup to itself
![image](https://user-images.githubusercontent.com/7021883/122691922-8e93f580-d275-11eb-81f8-a788c59cfdb7.png)

![image](https://user-images.githubusercontent.com/7021883/122691947-9eabd500-d275-11eb-99e0-9a7e56971c94.png)

2. Create one record for this object...then a few children
We created one parent and 2 child records.

![image](https://user-images.githubusercontent.com/7021883/122691988-d9ae0880-d275-11eb-8842-664426bd95dd.png)

3, 4 and 5. Setup the timeline configuration metadata type
This is how I setup the metadata.
a) Navigate to the lookup field (Parent Memo) in my case and note down the 'Relationship Name'
![image](https://user-images.githubusercontent.com/7021883/122692035-35789180-d276-11eb-8e51-3bcdb58127e3.png)

b) Use this relationship name to then setup the metadata
![image](https://user-images.githubusercontent.com/7021883/122692078-74a6e280-d276-11eb-9057-4f2780d218d5.png)

6 and 7. Then add the Time Warp component to the record that has children.

![image](https://user-images.githubusercontent.com/7021883/122692098-9011ed80-d276-11eb-9081-bbfebd9b50e1.png)

So based on the above setup it seems to be okay. Can I get you to check the setup and then perhaps upload screenshots based on your setup so that we can replicate the issue?

**Comment by marcbourlon** [comment]
Hello Dave, and congratulations for being so fast!!! I wish Salesforce 
support was as fast and efficient 😂

I'm baffled, and very grateful for your email! While going through each 
step to answer you, I realized my mistake: I was using records whose 
children are too old to show... Feeling suddenly lonely...

Should I close the bug report?

May I open a feature request for being able to go further in the past? 
My client is a doctor, who sees patients on a very long timespan (10+ 
years) though without too much data (timeline won't be crowded, and not 
too much performance issue).

Big thank you, and so sorry for wasting your time...

Marc Bourlon

**Comment by deejay-hub** [comment]
No issue wastes our time so no need to apologise. It's always good to connect with the community and helps identify areas for improvement. We're glad you managed to get it working.

We'll close this bug report but by all means open a new feature request for the timeframe requirement. Currently you can go back 5 years and into the future 5 years (10 years total). So would be good to understand if you'd like to see 10 years history and 10 years into the future (20 years total) - or if just the history was the important part.

Thanks again for trying the component and providing feedback.
