### ISSUE TITLE
Not all records of standard and custom objects are plotted in a selected timeframe

### ISSUE THREAD

**Issue by thedja** [deejay-hub/timeline-lwc#135]
**Describe the bug**
I included TimeWarp on standard object Account to plot Tasks, Events, Opportunities and a custom object called Notes.
For one particular Account there are an extensive number of tasks (with an soql query I got 136 record in the periode 4 months before and 1 month after today) and events (166 in the same time frame) and few Notes and Opportunities. The issue is that some tasks and events are not plotted at all, even when filtering only tasks or events, selecting different time frames. But when I deactivate one or two types of objects from the "Timeline Configuration" custom metadata types, more events/tasks appears to be plotted. Find below two screenshots with the same timeframe but different configuration for plotted objects :
1. Tasks and Events are active : https://ibb.co/ZMfwzpr
2. Only Events are active  : https://ibb.co/Ln7TNkG

Notice the period from January to April 2021, when both objects are active it is empty but when only events are plotted there is a lot of records.

Is there any limitation on the number of objects to be plotted ? As I did not find any mention of that in the documentation and few hundred records is well below the 50.000 SOQL query limitation.
I also tried debugging in the dev console but did not find any exception.

Thank you for your help.

**Additional context**
For other Accounts with fewer records to be plotted, all tasks, events and notes appear to be showing correctly.

The SOQL query I ran to get the number of Events/Tasks related to the Account : 
```
SELECT Id, (SELECT Id, Subject, StartDateTime FROM Events WHERE StartDateTime>= LAST_N_MONTHS:4 AND StartDateTime <= NEXT_N_MONTHS:1 ORDER BY StartDateTime DESC)
FROM Account Where Id = 'ACCOUNT_ID'

SELECT Id, (SELECT Id, Subject FROM Tasks WHERE ActivityDate>= LAST_N_MONTHS:4 AND ActivityDate <= NEXT_N_MONTHS:1) FROM Account Where Id = 'ACCOUNT_ID'
```

**Comment by deejay-hub** [comment]
Hi @thedja. In order to replicate the issue we would need you to supply the date (used to plot) and the object type (Task, Event etc) in a 2 column spreadsheet.

So the spreadsheet would look like

Date, Object Type
01/01/2010, Task
02/01/2011, Event
01/08/2021, Opportunity

If you'd be willing to attach such a file we can investigate the issue thoroughly.

If not then we'd be guessing at what your issue is. We suspect that due the the high volume of records what you're seeing is not a gap but that the plotted dots are being vertically pushed down to the point you can no longer see them. We'd be able to confirm this and potentially make the experience better for large numbers of tightly clustered records if you'd be willing to share how the records are clustered.

**Comment by thedja** [comment]
Hello,

Please find [here](https://www.filemail.com/d/kypltfizkdinxlc) the requested spreadsheet.
Let me know if you need anything else to troubleshoot the issue.

Best regards.

**Comment by deejay-hub** [comment]
Okay we uploaded the dates in question for a new Account in a fresh install. The sample data had 265 events and 213 tasks (we ignored Files for now since they are a pain to upload and there were only a handful of them). We couldn't replicate any gaps as can be seen from the screenshot below. Where we see 478 items.
<img width="1424" alt="CompanyTest-01" src="https://user-images.githubusercontent.com/7021883/123572401-7e4cbf00-d80f-11eb-9a3e-298e699a9ae7.png">

We probably need a fuller data set to replicate it...
a) Find the timespan you are plotting by editing the lightning page
<img width="1436" alt="TimeRange" src="https://user-images.githubusercontent.com/7021883/123572652-e69ba080-d80f-11eb-8bb6-dd6e7668f515.png">

b) Find the types you are trying to plot for the Account and give us all active types listed. As can be seen below these are the types I will plot for Account in my Org
<img width="1122" alt="ActiveAccountConfig" src="https://user-images.githubusercontent.com/7021883/123572902-4c882800-d810-11eb-84bc-93d50ce5d588.png">

c) Then for all the above active types....query for all the corresponding data in your time range.
So for Tasks based on your screenshot we would need the last 2 years worth and those 1 year in the future. We would need this for each active type.

**Comment by thedja** [comment]
Hello @deejay-hub ,
Please find bellow the required details for your investigation :
a) Timespan : 2 years in the past and 0.5 year in the future
b) Plotted types : Tasks, Events, Notes (Custom Object), Contacts, Cases & Opportunities
c & d) Records & plotted types details in the following [file](https://www.filemail.com/d/dxdbgydkdnysyoq)
e) We are not using Person Accounts

**Comment by deejay-hub** [comment]
Great. We appreciate your time doing this and makes replication much easier. As a result we have tracked down the cause.

The issue is that Time Warp tries to plot the 'Description' field in the hover for all Tasks and Events. Since Tasks and Events don't support the UI API we supply a fallback Tooltip Field in the metadata setup that can be used as a fallback. We picked 'Description' for Tasks and Events. Sadly, turns out this is a bad decision since Description is a Large Text Area. 

Whilst we look at the route cause more fully you can help us verify our thoughts. We think that by making the following changes you should 'see' all Tasks and Events (together with your other objects).

Step 1: Navigate to Account_Tasks and modify the 'Fallback Tooltip Field' to replace 'Description' with 'Status' and Save
![image](https://user-images.githubusercontent.com/7021883/123725684-d77d2700-d8d1-11eb-8c23-762b45800a74.png)


Step 2: Repeat for Account_Events but since Status is not a field on Event use 'Owner.Name' and click Save
![image](https://user-images.githubusercontent.com/7021883/123726129-c254c800-d8d2-11eb-9b5f-78bab711d2ef.png)

Step 3: Navigate back to your Account and refresh the browser.

**Can you confirm this resolves the issue please?**

**Comment by thedja** [comment]
@deejay-hub
I confirm changing the Fallback Tooltip Field from "description" to any non long text area field solves the problem.
That means we should avoid putting long text fields in the Tooltip or compact layout 
Thank you for your help.

**Comment by deejay-hub** [comment]
Compact layout should be fine but we'll be making the following changes
1. Update the configuration guide to ensure that people are aware they shouldn't use Large Text Area fields. Instead use standard text fields or formula fields.
2. That the next version has default values for tasks and events that doesn't use Description

**Comment by thedja** [comment]
Great job, Thank you.
