### ISSUE TITLE
Time Warp doesn't load when user non admin users when ActivityHistories is added

### ISSUE THREAD

**Issue by YuvalAviramSJ** [deejay-hub/timeline-lwc#159]
**Time Warp version**
1.9
**Describe the bug**
When adding the ActivityHistory to the metadata, If the user isn't an Admin Time Warp doesn't load correctly. Instead you see an apex error: "There is an implementation restriction on ActivityHistories. When you query this relationship, security evaluation is implemented for users who don't have administrator permissions, and no other filters may be applied to the aggregate query."

**To reproduce**

1. Add ActivityHistory object to the metadata settings with Account relationship.
2. log in as a non admin user
3. open any Account page

**Expected behaviour**
time Warp will load as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/72464503/145247917-8762d14e-6c3c-4755-94d7-82414b24232a.png)

**Desktop (please complete the following information):**

-   OS: [windows]
-   Browser [chrome]
-   Version [Version 96.0.4664.45]

**Additional context**

**Comment by deejay-hub** [comment]
This looks like a current Salesforce known issue with the Winter '22 release.

https://trailblazer.salesforce.com/issues_view?id=a1p4V000001SpoiQAC&title=error-malformed_query-when-end-users-scroll-down-through-activity-history-related-list-with-more-than-450-results.

It would be great if you could answer the following:

1. Can you confirm to see how many ActivityHistory records you have for each Account. The known issue is impacting parent records with more than 500 records in ActivityHistory.

2. Are you plotting ActivityHistory because you only want Tasks and Events that are in the status 'Closed'? <-this helps determine if a workaround is available.

**Comment by deejay-hub** [comment]
@YuvalAviramSJ you have 2 options

1. Reduce the timespan by editing the page and reducing the time span queried to bring the total number of records below 500. Edit the page the Time Warp component is on then reduce the value in the Historic and Future periods.

![image](https://user-images.githubusercontent.com/7021883/145772243-18551930-e6bf-4f10-974f-3b90d0ca50c1.png)

2. Inactivate the custom metadata types associated OpenActivities or ActivityHistory and use Tasks instead. These are both provided out of the box. 

In the meantime we'll consider this as an option for an enhancement to allow more than 500 records per parent. It won't make the February release though.

**Comment by deejay-hub** [comment]
Modifying ActivityHistory and OpenActivities to adhere to constraint on WHERE and LIMIT clauses that should allow non admins to see these child records for up to 1,000 records.

**Comment by deejay-hub** [comment]
For the Luyten release you can now add ActivityHistory and OpenActivities for users without 'ViewAllData'. It's limited to 1,000 records split between Open Activities and Activity History records (500 each) for the parent record the Time Warp is on. For most use cases this will suffice. New release targeting 1st week Feb 2022.
