### ISSUE TITLE
Please allow Zoom range to be selected freely

### ISSUE THREAD

**Issue by sak-hai** [deejay-hub/timeline-lwc#186]
**Is your feature request related to a problem? Please describe.**
We quite like this component but we plan multiyear projects several years ahead. Within green energy sector it is usual that projects tend to take time complete. Now the user has to re-zoom every time viewing the component. It it takes a year  to develop the project and 1-2 to complete it.

**Describe the solution you'd like**
Please allow zoom to be set freely to any number of days OR at least up to 365 days in order to zoom in a rolling year.

**Describe alternatives you've considered**
We were thinking to customize this component but would rather like you add this feature. It may be useful for others.

**Additional context**

**Comment by deejay-hub** [comment]
Sounds like a reasonable request. Since more days = more records people need to be aware that we originally restricted it to prevent excessive amounts of data from being plotted by default. Moving to allow 365 days sounds like a good compromise and perhaps puts the onus on the admin to make the right choice on the value.

Available in the next release. Epsilon. End of June 2022.
