### ISSUE TITLE
Display different fields in the pop-up for tasks and events.

### ISSUE THREAD

**Issue by stratops-skello** [deejay-hub/timeline-lwc#232]
Hello to all,
We love your work and our users are very satisfied, however we would need to display different fields in the pop-up for tasks and events.
We tried to set up a compact layout but it doesn't seem to work.
We have also changed the subject field to a description field to display the description but this does not totally meet the need. (cf screenshot)

We really need to be able to see these fields :
- Subject of the task/event
- Date of the task/event 
- Description of the task/event
- The owner of the task/event

Is there any solutions already in place? Or can we add custom code ?
Thanks for your help
<img width="1068" alt="Capture d’écran 2022-12-12 à 18 23 31" src="https://user-images.githubusercontent.com/106674310/207113541-717203eb-fc11-45ab-89f4-b61c6b9fad4f.png">

**Comment by deejay-hub** [comment]
The Activity object does not support the UI API. That is why it doesn't support changing the Compact Layout. The best solution is for Salesforce to add support. Given I have no idea if/when this will happen in the meantime you have loosely 2 options
1. Change the code to suit your needs - it's all in this repo.
2. Use the Fallback Tooltip Field configuration and a Formula Field
For objects not supported by the UI API we created a field on each metadata record to allow people to specify a fallback tooltip. Right now yours is set to **Status**. You could override this with the value of a custom formula field. I created a formula field called Activity_Summary__c

<img width="818" alt="image" src="https://user-images.githubusercontent.com/7021883/207162472-bbcffd4a-dc41-4cde-9a62-eb0d5ecfb765.png">

In this formula I concatenate the fields I want to see.

Then I just add this to the metadata record. In the case below I ask to see this field for the Contact/Task relationship by using the Fallback_Tooltip_Field__c field.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/7021883/207162883-67e49e05-295d-4a63-8226-43a6ade4c280.png">

Then when I am on the Contact record and hover over a Task I see this field in the hover

<img width="792" alt="image" src="https://user-images.githubusercontent.com/7021883/207163046-93444fee-83b5-4539-b005-92425b7c4e24.png">

The only issue you'll have is with **Description**.  We strongly recommend NOT to use a large text area field. It will create performance and scale issues. That is why you can't use these types of fields in related lists or formula fields. If you really needed to see it you'd have to compromise and create a new field of type text (255) and copy the first 255 chars into it - then refer to it in your formula field.

Since we have a workaround and Salesforce is likely to add UI API support in the future we'll close this issue as we won't be adding any new functionality.
