### ISSUE TITLE
Add plotting of Account History dates?

### ISSUE THREAD

**Issue by ThomasAlbrt** [deejay-hub/timeline-lwc#233]
Hello 👋

First, thanks a lot for this great component!

In addition to the plotting of objects, our team would like to plot specific events from **Account History**.
Especially the changes of status.

<img width="1536" alt="Xnapper-2023-01-23-12 23 10" src="https://user-images.githubusercontent.com/13610998/214028544-6ba48713-e931-4751-ba4f-3cad349c2d43.png">

Is there a way to achieve this in your opinion?

Thanks!

**Comment by deejay-hub** [comment]
The best way to achieve this currently is to modify the code directly and package it up in your Org.

We have put a validation rule to prevent History objects from being plotted. People could deactivate it and add the History object to the metadata and get ALL records to plot, but this is not recommended given the data volumes - hence the validation rule to discourage it.

Filtering to one field would be a good compromise but making this work in a generic fashion, so that people could plot History based on **any** parent sObject would be possible, but time consuming to code.

However, if someone in the community works on it and sends me the pull request then I'd be happy to incorporate it! I'll leave this open for a few weeks for visibility to see if others are interested in adding the functionality.

**Comment by ThomasAlbrt** [comment]
Thanks a lot for the detailed response.

I might able to dig deeper in a few weeks, I'll let you know if I do.

**Comment by brettkobo** [comment]
This is also a really cool feature! We plan on potentially just timestamp another object instead of using the history object so we can visualize changes to the account over time.

**Comment by deejay-hub** [comment]
Haven't had an update from the community on this. My thoughts are that record changes over time are best visualised differently from how Time Warp works today. This might be a good idea for a separate component.

Will keep this open for another 2 months to see if anyone from the community has solved for this but ultimately will close as something we won't actively work on.
