### ISSUE TITLE
Console App: When Contact is opened as subtab of Account then Timewarp on Account shows an error

### ISSUE THREAD

**Issue by juhalassila** [deejay-hub/timeline-lwc#238]
Repro
1. Create records: Account with a related Contact.
2. Setup Time Warp both on Account and on Contact.
3. In Setup > App Manager > [Console App] set a Navigation Rule: Contacts open as Subtabs of Account.
4. In Console App, navigate to Contacts.
5. Open a Contact.
6. Observe Contact: Time Warp = OK.
7. Observe Account: Time Warp = NOT OK.
8. Observe error text: Houston..we've had a problem. Cannot read properties of null (reading'redraw').

However, when I open the Account so that it opens as a Workspace tab then Time Warp of the Account is OK.

**Comment by deejay-hub** [comment]
Hi @juhalassila thanks for raising this. We've reproduced the issue and will get back to you when we've had a chance to do a detailed analysis on what's happening.

**Comment by deejay-hub** [comment]
The component loads but the offset width is zero for the parent tab. This creates the issue that the records and minimap plot in the first pixel. This occurs since the DOM is not updated until the tab has the focus.

We'll add some error handling in the next release to help with a work around. When you click the parent tab we'll display an error
<img width="1015" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/7a385861-67e6-4c35-8988-9ee96bbfc383">

When the workspace API is GA we'll add some logic to auto refresh the timeline when the tab has focus.
