### ISSUE TITLE
Time warp parent record of the timeline displayed on a lead

### ISSUE THREAD

**Issue by JulieDelastre** [deejay-hub/timeline-lwc#242]
**Time Warp version**
1.11

**Describe the bug**
Hello,
I wanted to change the parent record chosen to display the timeline on the lead objet, and choose the objet account (because we have lookup on accounts on our leads). It works on our sandbox, but when I want to deploy on SFDX, I have an error message. Could you help me on this ?

**To reproduce**
Steps to reproduce the behavior (cf screen)

Error : 
=== Component Failures [1]

 Type  Name             Problem                                                                                            
 ───── ──────────────── ────────────────────────────────────────────────────────────────────────────────────────────────── 
 Error Lead_Record_Page In Lightning component bmpyrckt:timeline, property timelineParent has an invalid value account__c.
```

![Capture d’écran 2023-03-27 à 11 57 09](https://user-images.githubusercontent.com/120714065/227911910-3ed78ef7-2016-4325-a4d5-ce8a4cf1bf0b.png)

![Capture d’écran 2023-03-27 à 12 08 37](https://user-images.githubusercontent.com/120714065/227911930-03240b1d-2890-4ab8-a460-fd4a2649a439.png)


Thanks a lot for your help !

**Comment by deejay-hub** [comment]
Hi @JulieDelastre. Just to catch up on the config can you confirm that the field used on the Lead object to lookup to the Account has this field already been deployed to production? 

If so can you check the values for **Label** and **API Name**. Are the values for the field identical to those in your sandbox?

**Comment by deejay-hub** [comment]
Hi @JulieDelastre just wondering if you still needed help with this issue? Last comment was seeking clarification that the production and sandbox environment both had the same field deployed with the same API Name and Label. Secondly we are hoping to confirm if you're using the managed package?

**Comment by JulieDelastre** [comment]
Hi, sorry for the delay, yes I confirm the field used to the lookup is already deployed, i've just rechecked now.
Regarding to label and API name it's the same. Yes I confirm we are using the managed package version of Time Warp !

**Comment by deejay-hub** [comment]
This is a bug. The only work around currently is to deploy using the default option for parent then updating after the page layout is deployed.

**Comment by louisdauvois** [comment]
Hi having the same issue, any idea on How to patch it ?

**Comment by deejay-hub** [comment]
The only workaround currently is to deploy using the default value then in the target environment edit the page and select the Parent needed.

**Comment by deejay-hub** [comment]
This is fixed in the current main branch. We have aligned values displayed to the API name of the parent field. Previously it used the label of the field when displaying but saved the API name to the metadata. We've simplified it to cater for the additional defect we had that some people had duplicate labels displayed without being able to see the API name they weren't sure which field to select.

<img width="316" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/75ef4fd1-a789-4915-b5f8-83020700e57f">

If you're comfortable you can check out the latest code and check to see if it works for you. @louisdauvois @JulieDelastre we plan on releasing an updated version to AppExchange but need to address other issues first.
