### ISSUE TITLE
Apex error: SOQL statements cannot query more than 20 different child types.

### ISSUE THREAD

**Issue by nduns** [deejay-hub/timeline-lwc#246]
**Time Warp version**
V1.11

**Describe the bug**
I've added a new Custom Object to the Timeline to display on a Person Account. Had no issues adding Custom Objects in the past and have copied my steps taken previously (and refered to your instructions in [Quip](https://quip.com/6yvoAcBukqZB)). Am getting an error message in the Timeline: "Apex error: SOQL statements cannot query more than 20 different child types."

**To reproduce**
1. Configue new Timeline Configuration to display on Person Account
2. Make Active
3. Go to location in Person Account where Timeline is displayed to see the error message: "Apex error. SOQL statements cannot query more than 20 different child types." 
4. When I make the new configuration inactive, the timeline works as expected.

**Expected behaviour**
Custom Object record expected to display on Timeline

**Screenshots**
![image](https://user-images.githubusercontent.com/13972398/236115957-680b77c8-4d98-4bd9-b4fd-07eafcb6a764.png)
![image](https://user-images.githubusercontent.com/13972398/236116030-525caf77-6b8c-46e3-ae29-291431db879b.png)

**Desktop (please complete the following information):**

-   OS: OS Ventura v13.3.1 (a)
-   Browser Chrome Version 
-   Version 113.0.5672.63

**Additional context**
On top of the existing (standard) configurations provided in the package, I have 14 custom objects displaying on the Timeline for PersonAccounts.

**Comment by nduns** [comment]
Found this: 

> How many different types of related records can I plot?
> 
> We use sub queries to get the related records to your parent. Currently this has a limit of 20. So for a specific parent record you can include up to 20 related child record types.
>

**Comment by deejay-hub** [comment]
Hi @nduns . This limitation is in the docs as you found. We use relationship queries to support the metadata setup. This currently mean were bound by the limits Salesforce imposes. See the link below to the official docs.

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_query_limits.htm

**When you design SOQL relationship queries, there are several limitations to consider.**
No more than 20 parent-to-child relationships can be specified in a query.

We love you're trying to plot more than 20 though! We don't plan on providing a work around to allow more since 20 since it creates other scale issues for us.
