### ISSUE TITLE
Tracking for fields on an object

### ISSUE THREAD

**Issue by captjkirk** [deejay-hub/timeline-lwc#250]
Love the Time Warp, but I am finding that there is a limitation when working on an object in which you're doing project management. 
Objects in which we manage projects hold several dates and milestones which are not objects- just fields. it would be great to be able to show these fields on our timeline and be able to show spans for some (similar to how a Gantz chart would).

Would love to be able to configure tracking for an object to include fields (as well as related objects) from the object (Date fields) which would plot on the timeline. Option to show the date for a span of time would be an awesome add as well!

**Comment by deejay-hub** [comment]
Hi @captjkirk thanks for suggesting these.

We don't plan on adding the capability to support fields on the same object since project management isn't our main focus and isn't where we see Time Warp's unique value prop. There are other better PM tools out there.

As for the time span. That's something we're interested in and has been asked for before. We will close this issue but keep this one open. https://github.com/deejay-hub/timeline-lwc/issues/107
