### ISSUE TITLE
Time Line/ Range Limits 

### ISSUE THREAD

**Issue by safou** [deejay-hub/timeline-lwc#252]
For the use of Custom Objects it would be helpful to be able to adapt the limits of the range to the custom object. E.g. 
if the custom object has to custom date fields "Start date" and "End Date" the zoom rage or the limits would be these two dates

**Comment by deejay-hub** [comment]
Hi @safou. Would you be able to clarify the request for us? It is unclear to us what you're after here. As far as we can tell there are 2 ways to interpret your request.

1. I have a custom object with 2 fields - start and end date. I want the timeline to only show a date range between these 2 dates. Only child records that fit between these dates should be plotted
2. I have a child record with 2 dates - start and end date. I want to plot a span of time when each record is plotted. That way instead of a single plot I see a visual indication of how long each child record took.

Is it 1 or 2? or something else?

**Comment by safou** [comment]
Hi @deejay-hub it is 1. So a way to define by myself the date range on a custom object with its two custom date fields startdate and enddate

**Comment by deejay-hub** [comment]
Okay we'll try a few options to see if we can make something work

**Comment by deejay-hub** [comment]
The way we've decided to handle this is to add the ability to base Time Warp on the earliest and last record found when querying across all records.

<img width="327" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/faddb22f-e67d-4a11-9587-7d059218c9ed">

This allows people to use the Inclusion Field on the metadata records to filter for specific time periods. So you could create a formula field on the Child Object that was true if the x date >= date field on the Parent.

Implementing based on a date field on the object is problematic since the Parent Object can change in the design time attributes and requires us to add new attributes.
