### ISSUE TITLE
Using Compact Layout is not working in the Timeline component for Work Step object related to a Work Order even though Work Step is supported by UI API

### ISSUE THREAD

**Issue by goncaloteixeiracosta** [deejay-hub/timeline-lwc#253]
**Time Warp version**
1.11

**Describe the bug**
Try to display Work Step records in the Timeline, but seems is not picking up the Compact Layout when 'Fallback Tooltip Field' is empty . It displays an error message we hover the Work Step icon in the timeline even though Work Step is supported by UI API. You can see the error message in the screenshot attached to the bug report.

**To reproduce**

1. Go to Timeline component on the Work Order record page.
2. Hover one Work Step record related to the Work Order in the timeline.
3. See error in the screenshot section.

**Expected behaviour**
Expecting that it would pick the Work Step Compact Layout when 'Fallback Tooltip Field' is empty and it displays the fields in the compact layout when we hover the Work Step icon in the timeline.

**Screenshots**
Error Message Screenshot:
<img width="379" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/16195102/1bd53ed7-3bff-4bc5-98a5-b78d0e792da7">

Work Step Configuration:
<img width="633" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/16195102/62b4a3aa-f0ae-40f1-92d9-38490fc32cfd">

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome
-   Version: 117.0.5938.92 (Official Build) (64-bit)

**Additional context**

**Comment by deejay-hub** [comment]
Hi @goncaloteixeiracosta. This looks like a Salesforce bug.

Steps to replicate:
1. Create a LWC with the following:
<template>
    <lightning-record-form record-id="<ValidWorkStepId>" object-api-name="WorkStep" layout-type="Compact" columns="2"
    mode="readonly">
  </lightning-record-form>
</template>

2. Place onto a page layout.

Here you'll get the same error as you reported. This should work according to the documentation.

For now the only workaround is to use a fallback field.

Since there is little we can do to influence the issue getting fixed by Salesforce - and because there is a workaround - we'll close this issue.
