### ISSUE TITLE
Support for RecordTypes

### ISSUE THREAD

**Issue by mrcdsouza** [deejay-hub/timeline-lwc#27]
We use an object called Work Order to represent field service work and use RecordTypes (Break-Fix, Scheduled Maintenance, Long Term, Project, etc.) to distinguish between one and another. I would like to define configuration entries via RecordTypes with different icons/tooltips/compact layouts etc.

**Comment by deejay-hub** [comment]
Thanks for the suggestion. I'm no expert in Field Service Lightning objects or use cases but the request to segment based on type or record type seems to be a great idea. This one needs help to strategise the best way to do this.

**Comment by mrcdsouza** [comment]
I'll be glad to help out here as you have an awesome component and made it very configurable. Adding a few more tweaks o distinguish between RecordTypes and Statuses for example, would make it very compelling to the end user.

**Comment by jackdough** [comment]
@deejay-hub, I can contribute as well. This is an amazing component and I would love to have this feature as well.

**Comment by deejay-hub** [comment]
@jackdough thanks for the offer to help. I'd be really interested in how people suggest this is tackled. I would need to better understand the use cases people want here. For example - is it the ability to see different icons for different types or statuses - or the ability to quickly find these records?

**Comment by jackdough** [comment]
@deejay-hub, a simple example would be a case where I have different RecordTypes for Opportunities. While one may be a financial Opportunity another may be a `connection` opportunity in which case I want the snapshot to be different.
The simple solution would be to allow the creation of different configurations based on RecordType so they can be treated as different Objects (in essence). A simpler solution may be to allow custom filtering, this would allow limiting by other fields as well (though I don't have a good use-case for that).

**Comment by mrcdsouza** [comment]
@deejay-hub My use case is about an asset's lifecycle in Salesforce Field Service. An Asset can have many types of Work Orders associated with it. For example, there might be different (recordtypes - Field, Remote, Depot) Work Orders for an asset. It would be great to see different icons/colors for each Work Order type on the timeline to get a complete understanding of the asset's lifecycle.

**Comment by deejay-hub** [comment]
@mrcdsouza got it. What about filtering - is that important? If you can **see** the difference (icon and colour) would you also be expected to filter them too? - So the user might want to see only the 'Depot' Work Orders plotted - or would filtering by just Work Orders still be okay here? I assume if you prioritised the 2 requirements (viewing and filtering) then viewing them would be your priority?

**Comment by mrcdsouza** [comment]
@deejay-hub Yes Dave. Viewing with icon & color will be #1 and filtering (Open/Closed, High/Low Priority, etc.) would be #2. Thanks again for this LWC.

**Comment by TobsenMB** [comment]
This Would be a really interesting Use Case for us as well. 
We Use Record Types quiet frequently. 
The ability to differentiale Icons and beeing able to filter them would benefit our User. Especially on bigger Accounts the timeline can get a little crowded otherwise.

**Comment by mayday6971** [comment]
I would love to see this functionality as well. I think a simple new checkbox on the metadata row to show the RecordType would be great!

**Comment by brettkobo** [comment]
This would be a extremely helpful feature. We utilize the task object to store all different kinds of activity from sales to marketing like pageview and form submissions. Right now we are going to use this app to visualize the entire task object but it would be extremely helpful if we could add some type of sub-filter based on recordType or other picklist fields. We might even look at look at contributing if we need this function.

I was thinking maybe on each meta record you could have a field that is the like sub-filter field that brings in another filter criteria that can be added to the actual app. I imagine this would flow pretty will with the SQOL calling the data because based on the sub filter it could dynamicly change that data. 

Right now we are just going to display the entire task object with some filtering with the inclusion field. I wish it was more dynamic. We are going back and forth on that or another custom object.

**Comment by deejay-hub** [comment]
Thanks @brettkobo for offering your help. Happy to hear your thoughts on the topic.  It's a challenging topic to solve since we have designed Time Warp to only execute one SOQL query with a bunch of sub queries for each child record. We might need to break that philosophy to meet this requirement - which could have scale and performance implications.

Ultimately someone cleverer than me needs to spend some time designing it.

**Comment by deejay-hub** [comment]
We've added dynamic icons and background colours to the latest release. Scheduled for AppExchange Jan 2024.
