### ISSUE TITLE
Apex Error...Aggregate query has too many rows for direct assignment, use FOR loop

### ISSUE THREAD

**Issue by Zer0frixion** [deejay-hub/timeline-lwc#291]
**Time Warp version**
Setup->Apps->Packaging->Installed Packages. What is the value in the Version Number column for the package Time Warp.

**Describe the bug**
![image](https://github.com/deejay-hub/timeline-lwc/assets/169618892/3877f170-1273-4b63-bd69-5fc14c540013)

**To reproduce**
Go to a very active contact record

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. This helps speed up the triage of the issue.

**Desktop (please complete the following information):**

-   OS: [Win 11
-  Chrome
-  Version 124.0.6367.201 (Official Build) (64-bit)

**Additional context**

**Comment by deejay-hub** [comment]
@Zer0frixion could you help us understand what a very active Contact record looks like for you?

We typically like to recreate the number of records and types that you're using to plot where possible. For that we need to know

1. The child object you're plotting for Contact. For this filter the Timeline_Configuration metadata type to show records where Parent Object = Contact and Active = True
<img width="1434" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/bd445f08-a71c-45da-ba28-385474ad34e5">

2. The values you use on the component itself for 'Future Time Range (Years) and Historical Time Range (Years)
<img width="1199" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/31af8105-2b7c-4a8f-9a60-572d8868b6c8">

3. The approximate number of records that fall into each type of object from 1. and the time range you selected for 2.
Our suggestion is to plot as few records as possible. Quality over quantity. Time Warp has been designed to highlight clusters of key interactions over time across Sales, Service, Marketing and custom use cases. The operative words are ‘key interactions’. Plotting thousands of records muddies the Time Warp with quantity. Only plot the key interactions and we suggest keeping the total number of records less than 500.

So to get the number of Tasks for the Contact you can run
SELECT count() from Task where WhoId='003dL000000WWmMQAW' WHERE <PositionDateFromStep1> >= LAST_N_MONTHS: x AND <=NEXT_N_MONTHS: y. Where x is the historical time range in step 2 and y is the future time range converted from years to months.

So if you asked to plot Tasks using CreatedDate and the historical time and future time range was 2 then the query would be
SELECT count() from Task where WhoId='<your_contact_id>' AND CreatedDate >= LAST_N_MONTHS:24 AND CreatedDate <= NEXT_N_MONTHS:24

In order to investigate thoroughly we would need counts for any child object over 100 records. Task and Event are good starting points.

**Comment by deejay-hub** [comment]
@Zer0frixion. In order to investigate further we would need to know the child objects you're plotting on the Contact parent object and some indicative record counts for each object.

**Comment by Zer0frixion** [comment]
Hi Dave...

Unfortunately, I have decided not to utilize the time Warp view. It slowed
down performance, and after living with it for a bit, I didn't find it to
be an actionable and material improvement in overall productivity.  It's
great looking, and if it didn't affect load time, i might stay with it.
However, there's already a lot of information on any given screen. I'm
looking to simplify views, not add to them.

I hope my feedback proves helpful.

Thank you...


www.schooleymitchell.com/niponneil
*Larry Nipon <https://www.linkedin.com/in/larrynipon/>*
*Strategic-Partner / Cost Reduction **Specialist*
*Click Here For A 1 Minute Overview <https://bit.ly/90SecAnimated2023>*
Hillsdale, NY 12529

P:  +1 (518) 851 1706

M:  +1 (917) 613 5224

***@***.***

LinkedIn
<https://app.grooveapp.com/url/ddrmcefndrkevem8n31qzk/aHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2luL2xhcnJ5bmlwb24vI2dyb292ZXN1bToxOTU0NDMyNjI4>

STATEMENT OF CONFIDENTIALITY The information contained in this email
message and any attachments may be confidential and legally privileged and
is intended for the use of the addressee(s) only. If you are not an
intended recipient, please: (1) notify me immediately by replying to this
message; (2) do not use, disseminate, distribute, or reproduce any part of
the message or any attachment; and (3) destroy all copies of this message
and any attachments.
