### ISSUE TITLE
Events logged against contacts are not shown on the account's timeline

### ISSUE THREAD

**Issue by deepak-UNOPS** [deejay-hub/timeline-lwc#292]
**Time Warp version**
Version: 1.12

**Describe the bug**
The Event record was created with Contacts of 2 different Accounts and Related to 1st Account but the Event is only visible on the 1st Account not on the Accounts of those Contact which which are mentioned in the Event.

**To reproduce**

1. Go to 'Account' 
2. Click on 'Event' to create a new Event.
3. Enter 1st Account in the "Related to" field and select 2 different Contacts of 2 different Accounts in the "Name" field.

**Expected behaviour**
The created Event record should appear in the Time Warp component of the Accounts of those Contacts which are mentioned in the Event record as it is visible in the "Related to" Account.

**Screenshots**
as you see from the screenshot below, an event from the gmail calendar is logged into Salesforce using Salesforce extension.

One Account ‘Argentina’ is tagged (related to this event)

One Contact Jose is tagged which has Account ‘Phillipines’

One Contact Anisha is tagged which has Account ‘Accenture’

The event is only appearing on the timeline of Account - Argentine and is not appearing on the timeline of ‘Phillipines’ & ‘Accenture’

 

![image](https://github.com/deejay-hub/timeline-lwc/assets/156095721/c941076a-2a46-420e-97eb-4a73626953e9)

Accenture and Phillipines
![image](https://github.com/deejay-hub/timeline-lwc/assets/156095721/1ba89996-9ca2-4bd8-b93a-f4c100d6f97b)

Argentina
![image](https://github.com/deejay-hub/timeline-lwc/assets/156095721/eb00f4bd-d7ca-46d6-a033-23cb3dcb1e3e)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome
-   Version: 124.0.6367.209

**Comment by deejay-hub** [comment]
Hi @deepak-UNOPS . Have you checked the FAQ guide? For Tasks and Events on the Account object you might find that switching to OpenActivities and ActivityHistory work for you.

Steps here -> https://quip.com/6yvoAcBukqZB#dDRACAgmIoY

Then search for the section called '**What about indirect relationships? The standard Account timeline shows tasks and events not directly linked to the Account. Can Time Warp do something similar**?'

This shows you screenshots on how to disable Tasks and Events and enable OpenActivities and ActivityHistory on the Account object.

Try it and let us know if it helps resolve your issue.

**Comment by deepak-UNOPS** [comment]
Hi @deejay-hub, thank you for your response. I followed your instructions, but now the Activities that were associated with the Accounts have also disappeared.

**Comment by deejay-hub** [comment]
@deepak-UNOPS . These are the steps we took. Let us know if they differ from what you describe.

We created 2 Account records and under each Account created 1 contact.
Account One
  -- Contact Account One

Account Two
  -- Contact Account Two

We then turned on the ability to associate a task to multiple contacts
<img width="796" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/42b3b2f2-cdef-426b-9c40-348c01c3a6fe">

We then created one event record. We selected Account One as the Related To field value and populated the Name field with both new Contacts created above

<img width="1696" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/c9dd351d-f5e0-4026-b03d-ddb62bf4c78b">

When we navigate to the Account One record and view Time Warp we see this.

<img width="1712" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/d52dbb97-7dc6-48b7-837f-6e0a92724ad8">

This shows the 'First Event' record created.

When we navigate to Account Two record and view Time Warp we see this.

<img width="1719" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/38d03c7a-4e04-4052-835e-95e4418f4d41">

We did this because we activated OpenActivities and ActivityHistories in the metadata and disabled the records corresponding to Tasks and Events for the Account parent object.

<img width="1455" alt="image" src="https://github.com/deejay-hub/timeline-lwc/assets/7021883/6677feaf-46d2-4fe0-96ce-dcad24712dc8">

**Comment by deepak-UNOPS** [comment]
Hello @deejay-hub , Thank you for your response. I followed your instruction as you gave above. This time the result was quite strange. I have changed the setting of configuration and Activity setting as you said above. 

![step 1](https://github.com/deejay-hub/timeline-lwc/assets/156095721/00733df5-281d-4e7a-8100-6a8fcac3755f)


After that, I created an Event on 1st Account with Contacts of 2 different Account :

![step 2](https://github.com/deejay-hub/timeline-lwc/assets/156095721/d8e9957c-c2a8-4b03-9627-2b8ac5cc0967)


It is visible on Accounton which I have created the Event and on the 1st Contact Josefina's Account : 

![step 3](https://github.com/deejay-hub/timeline-lwc/assets/156095721/f09b5baa-3419-42f0-8c8a-b1a23641f521)

![step 4](https://github.com/deejay-hub/timeline-lwc/assets/156095721/3cdd5104-ae2d-45a5-946b-38890fb6d497)


But the Event is not visible on the 2nd Contact Anisha's Account :

![step 5](https://github.com/deejay-hub/timeline-lwc/assets/156095721/e24ca552-cbc1-4f90-a1fc-0c8e895959c0)


Thank You.

**Comment by deejay-hub** [comment]
What does the Timeline Metadata look like for all records where ParentObject = Account. Similar to the last screenshot in my post?

**Comment by deepak-UNOPS** [comment]
As you can see in the below screenshots, I made the changes as you mentioned in the above comments : 

![Screenshot 2024-05-28 113759](https://github.com/deejay-hub/timeline-lwc/assets/156095721/c9aca6db-6899-4c08-ba95-c3d362d29dc5)

![Screenshot 2024-05-28 113905](https://github.com/deejay-hub/timeline-lwc/assets/156095721/717a43ba-ed1a-4556-a356-ef07882018f9)

![Screenshot 2024-05-28 113837](https://github.com/deejay-hub/timeline-lwc/assets/156095721/b1e8551c-3c3e-4783-af0b-77ee8ee623e7)

![Screenshot 2024-05-28 113935](https://github.com/deejay-hub/timeline-lwc/assets/156095721/d7dd8aaa-b724-4901-a011-764cb91f7e6c)

**Comment by deejay-hub** [comment]
Can you remove the value in the Inclusion Field - TEST_EMAIL__c. A boolean value here indicates if the record should be plotted or not. I would remove the value completely then confirm you can see the record first.

We need to remove the possibility that the value being returned is causing the record to be skipped.

**Comment by deepak-UNOPS** [comment]
Yeah, I did as you said but still it is not visible : 

![Screenshot 2024-05-28 115108](https://github.com/deejay-hub/timeline-lwc/assets/156095721/28a90118-6bb8-49c9-b048-88d464480086)

![Screenshot 2024-05-28 115129](https://github.com/deejay-hub/timeline-lwc/assets/156095721/008dcddd-f32e-4d8e-afa2-4a2b8dfb345d)

**Comment by deejay-hub** [comment]
Can you recreate the steps we tried with Account One and Account Two to see if it works and let us know what you see. We'll try and follow your screenshots.

**Comment by deejay-hub** [comment]
Also it's worth confirming that the event you expect to see isn't further down the timeline since you have many records a scroll bar appears and the event isn't necessarily always at the top.

**Comment by deepak-UNOPS** [comment]
Yeah, it is visible now. It was in bottom.

![image](https://github.com/deejay-hub/timeline-lwc/assets/156095721/d3751e27-23ba-4ecf-8a32-65acab0d96a7)

Thank You so much Deejay
