### ISSUE TITLE
The Emails are not visible when filtered by only Email Messages

### ISSUE THREAD

**Issue by deepak-UNOPS** [deejay-hub/timeline-lwc#293]
**Time Warp version**
1.12

**Describe the bug**
Emails are not visible when I checked the "Email Messages" checkbox.

**To reproduce**

1. When  I check the "Email Messages" checkbox then I am not able to see any Email : 

![Screenshot 2024-06-05 135136](https://github.com/deejay-hub/timeline-lwc/assets/156095721/71fea20a-1003-4013-ae35-48f7c71fd626)

2. But when I selected "Activity History", Emails are visible but along with Events, Call, etc. Activity Record : 

![Screenshot 2024-06-05 135846](https://github.com/deejay-hub/timeline-lwc/assets/156095721/01b6814f-448a-4366-84ca-12f886dcbc67)

Configuration is also Activates as per the official documentation at https://quip.com/ahFCA9VBEKtr

**Expected behaviour**
I should show the Emails only when filtered by Email Messages only.

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome
-   Version:  125.0.6422.114

**Comment by deejay-hub** [comment]
@deepak-UNOPS it's hard to look into issues without the exact steps to replicate. We are only guessing at what configuration you've done. We are guessing the following:
1. That you have turned on Advanced Email settings in Salesforce that logs emails in their own object called EmailMessage and as a Task (https://help.salesforce.com/s/articleView?id=000381944&type=1)
2. That you have added a new record to the Timeline_Configuration__mdt that asks to plot EmailMessages 

Time Warp mainly plots direct relationships from a Parent to a Child object. The Account object does **not** have a relationship to EmailMessage - so this configuration is invalid. Contacts have a relationship to EmailMessage so assuming the record is setup correctly in the metadata you can see this object on the Contact parent record.

Since there is no relationship from Account to EmailMessage there is no way currently to rollup using the EmailMessage object.

The only support Time Warp provides for _indirect_ relationships is for OpenActivities and ActivityHistory - which will plot Calls and Events.

**Comment by deepak-UNOPS** [comment]
No, We don't have any record  like 'Contact_EmailMessages' : 

![Screenshot 2024-06-07 131946](https://github.com/deejay-hub/timeline-lwc/assets/156095721/53be1975-d30e-4ac6-be52-1dc680985703)

**Comment by deejay-hub** [comment]
Time Warp doesn't support rolling up EmailMessage records from all contacts to a parent account.

The only support Time Warp provides for indirect relationships is for OpenActivities and ActivityHistory - which will plot Calls and Events.

Let us know if you need anything else.

**Comment by deepak-UNOPS** [comment]
Thank you for your response, can we display only Emails on the "Email Messages" checkbox? 

![Screenshot 2024-06-07 133001](https://github.com/deejay-hub/timeline-lwc/assets/156095721/a59be205-7e54-4dbb-97ea-b1433160ecea)

**Comment by deejay-hub** [comment]
EmailMessages are not a standard option. Did you add the value yourself by adding a record to the Account metadata?

**Comment by deepak-UNOPS** [comment]
Yeah, I just checked. It is created by someone in my Team. Ok, I understood. So, We have to go with the Activity History feature filter, right?

**Comment by deepak-UNOPS** [comment]
ok, Thank you
