### ISSUE TITLE
Support for External Objects

### ISSUE THREAD

**Issue by pedrozimmermannsoares** [deejay-hub/timeline-lwc#296]
**Is your feature request related to a problem? Please describe.**
Currently, Timeline-LWC does not support external objects in Salesforce. This limitation restricts the flexibility and integration capabilities for users who need to display data from external systems within their Salesforce instance.

**Describe the solution you’d like**
I would like Timeline-LWC to support external objects, allowing users to integrate and display data from external sources directly within the timeline component. This would enhance the usability and scope of the component, making it more versatile for various business needs.

**Describe alternatives you’ve considered**
An alternative solution could be to create a custom LWC component that fetches and displays external object data. However, this would require significant development effort and maintenance. Integrating this feature directly into Timeline-LWC would provide a more streamlined and maintainable solution.

**Additional context**
Including support for external objects would greatly benefit users who rely on Salesforce as a central hub for data from multiple systems. This feature would enable a more comprehensive view of timelines that encompass all relevant data, regardless of its origin.

**Comment by deejay-hub** [comment]
Hi @pedrozimmermannsoares. 

Technically External Objects work fine. We have just added a validation rule to discourage their use. This is because Salesforce doesn't support a subquery on External Objects that return more than 1,000 records. See [here](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_limits.htm?_ga=2.218482972.448010184.1718684362-1498422952.1709035923).

Since we allow people to look back up to 10 years we run the risk of hitting a governor limit very frequently.

Do you have any ideas on how support for External Objects can be implemented in a scalable way?
